test-credentials:
  webhookUrl: "https://discord.com/api/webhooks/1427895228852998205/cwIe8BAk2Dny-qNLRCuxfdjfVAITnBnsbmpU-h_QT0tIw1_2Qf3nC7T9q2YnxJDDktox"
  googleDriveId: "1gffgENDTnB1J5YKJbDfjWfz7lOhKEIQQ"
  accountNameRefund1Point5Percent: "fbc306km15"
  accountPassRefund1Point5Percent: "12345678"

prod-credentials-youtube:
#  webhookUrl: "https://discord.com/api/webhooks/1427895228852998205/cwIe8BAk2Dny-qNLRCuxfdjfVAITnBnsbmpU-h_QT0tIw1_2Qf3nC7T9q2YnxJDDktox"
#  googleDriveId: "1PAk2UaAKd2oLPcEcV0WZE4Tp05jFRQWc"
  accountNameRefund1Point5Percent: "fbc306km15"
  accountPassRefund1Point5Percent: "12345678"

prod-credentials-google:
#  webhookUrl: "https://discord.com/api/webhooks/1427895228852998205/cwIe8BAk2Dny-qNLRCuxfdjfVAITnBnsbmpU-h_QT0tIw1_2Qf3nC7T9q2YnxJDDktox"
#  googleDriveId: "1gffgENDTnB1J5YKJbDfjWfz7lOhKEIQQ"
  accountNameRefund1Point5Percent: "fbc306km15"
  accountPassRefund1Point5Percent: "12345678"