base:
  browser: CHROME
  timeout: 30
  headless: false
  multi-browser: false
  grid: false
  env:
    - prod-env-youtube
    - prod-env-google-search
  credentials:
    - prod-credentials-youtube
    - prod-credentials-google
    - test-credentials

prod-env-youtube:
  url: https://www.youtube.com/
  imageReportPath: src/output/reports/ExtentReports/screenshots/output_image.png
  reportPath: src/output/reports/ExtentReports/google-cloud-report.html
  pageUrls: {
    baseUrl: https://www.youtube.com/
  }

prod-env-google:
  url: https://www.google.com/webhp
  imageReportPath: src/output/reports/ExtentReports/screenshots/output_image.png
  reportPath: src/output/reports/ExtentReports/google-search-report.html
  pageUrls: {
    baseUrl: https://www.google.com/webhp
  }